### ISSUE TITLE
USER STORY: Delete Tasks

### ISSUE THREAD

**Issue by Joe-Brookes-Code-Institute** [Vishalchapa/MIMO#10]
- [x] Scenario: Successful Task Deletion
Given the user is viewing their task list,
When they click the "Delete" button next to a task,
Then the system prompts the user for confirmation and, upon confirmation, deletes the task from the list.

- [x] Scenario: Delete Completed Tasks
Given the user has completed tasks in their task list,
When they click the "Delete" button next to a completed task,
Then the system follows the same confirmation process and deletes the completed task upon confirmation.

**Comment by Anka-S** [comment]
show server error 500
